name: 'Nano API Build and Deploy Action'
description: 'Builds a new version of the Nano API and deploys it to the org, streaming the build logs to the action output'
author: 'Nano-API'
inputs: 
  api_key:
    description: 'API key for the org, obtained from the Nano API frontend'
    required: true
  envName:
    description: 'Environment name to deploy to'
    required: true
    default: 'dev'
  buildEnvVars:
    description: 'Environment variables to set for the deployed build'
    required: false
    type: object
runs:
  using: 'node20'
  main: 'lib/index.js'